name: zodgame

on:
  schedule:
  - cron: "0 0 * * *"
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Create non-root user
      run: |
        net user myuser MyPassword123! /add
        net localgroup Users myuser /add
    - name: Install requirements
      run: |
        runas /user:myuser "pip3 install -r ./zodgame/requirements.txt"
    - name: Run 
      run: |
        runas /user:myuser "python3 ./zodgame/zodgame.py '${{secrets.ZODGAME_COOKIE}}'"
    - uses: gautamkrishnar/keepalive-workflow@master
